spring:

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: booking
    password: booking
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/migration/user,classpath:db/migration/business

server:
  port: 8080